//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.DBEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Delivery_DBEntities : DbContext
    {
        private static Delivery_DBEntities _context;

        public static Delivery_DBEntities GetContext()
        {
            if (_context == null)
                _context = new Delivery_DBEntities();
            return _context;
        }
        public Delivery_DBEntities()
            : base("name=Delivery_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EntryHistory> EntryHistories { get; set; }
        public virtual DbSet<Move_Types> Move_Types { get; set; }
        public virtual DbSet<Package_Movings> Package_Movings { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
